### PR TITLE
Add properties for degraded and max response time

### PR DESCRIPTION
**Pull request by SaaldjorMike**
Depends on: https://github.com/bitfield/checkly/pull/4

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
@bitfield Now that https://github.com/bitfield/checkly/pull/4 has been merged, any chance you could take a look at this one as well?

**Comment by bitfield** [comment]
Excellent! Thank you. I'll merge this ASAP.

**Comment by SaaldjorMike** [comment]
Awesome. Thank you so much for creating the provider and me helping out!

**Comment by bitfield** [comment]
Merged as #6. Thanks again for the contribution! Much appreciated.

**Pull request closed without merging**
